# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: <%= $PLASTER_PARAM_FullName %>
# Generated on: <%= $PLASTER_Date %>

@{
    RootModule        = '<%= $PLASTER_PARAM_ModuleName %>.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '<%= $PLASTER_Guid1 %>'
    Author            = '<%= $PLASTER_PARAM_FullName %>'
    CompanyName       = '<%= $PLASTER_PARAM_ModuleCompanyName %>'
    Copyright         = '(c) <%= $PLASTER_PARAM_FullName %>. All rights reserved.'
    Description       = '<%= $PLASTER_PARAM_ModuleDesc %>'
    FormatsToProcess  = '<%= $PLASTER_PARAM_ModuleName %>.Format.ps1xml'
    PowerShellVersion = '<%= $PLASTER_PARAM_PowershellVersion %>'
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = @()
    # FunctionsToExport = @()
    # CompatiblePSEditions = @()
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
} 
